[WIP] Add version to generated package based on version of e-Crypt
eVision-oss/e-crypt pull request #15
Opened 2017-11-29 09:51 UTC by iarovyi

fix #14

2017-11-29 09:52 UTC, iarovyi commented
@antondimitrov @omer-demir
Please review pull request

2017-11-29 13:49 UTC, antondimitrov requested changes

2017-11-29 13:49 UTC, antondimitrov commented on src/eCrypt/Options.cs
> +        [Option('c', "content-version", Required = false, HelpText = "Version of the content to be encrypted. If provided it will be used for 'file version' property of generated executable")]
`-v` would be the preferred name

2017-11-29 13:49 UTC, antondimitrov commented on src/eCrypt/Options.cs
> +        [Option('c', "content-version", Required = false, HelpText = "Version of the content to be encrypted. If provided it will be used for 'file version' property of generated executable")]
I believe we will need extra validation to ensure the format is matching .net `version` class e.g. `1.1.1.1`

2017-12-07 09:04 UTC, iarovyi commented
![capture](https://user-images.githubusercontent.com/2605923/33706932-0139b902-db36-11e7-9016-ad7e8a783f98.PNG)

2017-12-12 13:55 UTC, Eugene1982 commented
PR was tested, @antondimitrov please merge

2017-12-12 13:57 UTC, antondimitrov commented
@iarovyi Can you please squash appropriately?

2017-12-13 08:07 UTC, iarovyi commented
@antondimitrov Squashed commits

2017-12-13 10:57 UTC, antondimitrov approved these changes

2017-12-13 10:57 UTC, merged