[WIP] Does not allow to use eVison logos by licensee
eVision-oss/e-crypt pull request #2
Opened 2017-10-06 14:36 UTC by iarovyi

In out project we have logos and of course we don't want people to reuse our logo.
We this pull request contains adjustments in the license that will not allow to reuse eVision logos.
But it still MIT based license that allow normal open source cooperation.

Text was adjusted by legal department.

2017-10-06 14:37 UTC, iarovyi commented
@damianh Please review pull request.

@antondimitrov, @Eugene1982

2017-10-09 09:23 UTC, damianh commented
Looks fine.

2017-10-09 09:31 UTC, damianh requested changes
Reviewed. Not happy that we've modified the MIT licence itself. Instead consider one of:

1. Specify the MIT license applies to source code only and add a second license for trademark based assets.
2. Remove the trademark assets from the repository (make them a private _build time_ concern) and revert the license to the standard MIT.

2017-10-09 09:31 UTC, damianh commented on LICENSE
> +MIT based License
Remove "based", it _is_ MIT, not based off of it.

2017-10-09 09:31 UTC, damianh commented on LICENSE
> +Logos shall remain the property of the licensor. Therefore, in case if the
This needs to be somewhere else and not modify the MIT licence itself.

2017-10-09 14:25 UTC, iarovyi commented
Applied first option.
@damianh

2017-10-11 09:03 UTC, damianh approved these changes

2017-10-11 09:04 UTC, merged